# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f79cb2bee4aca30c3e4e785d9fe496d94a29204d43beedc6c20ba8ccbc9c09f09286225d1e5411c2553d75fd2a06f9a90189121b71fba887ad132a01395e583

test:
  secret_key_base: 501fad6fec4941bbfe23f1a47cc703b670711f0c5d3d7b6051cec483ead7c00ca1c97adfa1382a51888f5750b93c88b83b1c0c3ff4a0d167f26e307f8ba92bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
